### ISSUE TITLE
Duplicate Data directory

### ISSUE THREAD

**Issue by jrames** [Zoha131/GitExplorer-iOS#1]
When cloning, I received the following warnings:

> warning: the following paths have collided (e.g. case-sensitive paths
> on a case-insensitive filesystem) and only one from the same
> colliding group is in the working tree:
> 
>   'GitExplorer-iOS/Data/Data.json'
>   'GitExplorer-iOS/data/Data.json'
>   'GitExplorer-iOS/Data/Repository.swift'
>   'GitExplorer-iOS/data/Repository.swift'

Looking at the repo, it appears you have a duplicate data directory - one in lower and one in upper case.

**Comment by Zoha131** [comment]
aah, at first it was `data` then I renamed it to `Data`. Thanks for reporting. I have removed `Data` directory and fixed it
